(*
NDTE: 4
NCPE: 30
NDME: 3
*)
2 0	sys_flag_types\sys_flag_	strArr_0_14	1024	1	USER	ARRAY	STRING	16			
2 0			0	14	
6 0	sys_flag_types\sys_flag_	arrByte0_127	1025	1	USER	ARRAY	BYTE	17			
6 0			0	127	
34 0	sys_flag_types\sys_flag_	Task_Name_eCLR	1028	1	USER	ARRAY	BYTE	17			
34 0			0	35	
36 0	sys_flag_types\sys_flag_	Task_Info_eCLR	1029	30	USER	STRUCT				
37 0		TaskStack	INT	3	0	
38 0		TaskPrio	INT	3	0	
39 0		TaskPeriod_us	DINT	4	0	
40 0		TaskWatchdog_us	DINT	4	0	
41 0		TaskPeriod	INT	3	0	
42 0		TaskWatchdog	INT	3	0	
43 0		MinDuration_us	DINT	4	0	
44 0		MaxDuration_us	DINT	4	0	
45 0		CurDuration_us	DINT	4	0	
46 0		MinDelay_us	DINT	4	0	
47 0		MaxDelay_us	DINT	4	0	
48 0		CurDelay_us	DINT	4	0	
49 0		MinDuration	INT	3	0	
50 0		MaxDuration	INT	3	0	
51 0		CurDuration	INT	3	0	
52 0		MinDelay	INT	3	0	
53 0		MaxDelay	INT	3	0	
54 0		CurDelay	INT	3	0	
55 0		unused_1	DINT	4	0	
56 0		unused_2	DINT	4	0	
57 0		unused_3	DINT	4	0	
58 0		unused_4	DINT	4	0	
59 0		unused_5	DINT	4	0	
60 0		unused_6	DINT	4	0	
61 0		unused_7	DINT	4	0	
62 0		unused_8	DINT	4	0	
63 0		unused_9	DINT	4	0	
64 0		TNameMaxSize	INT	3	0	
65 0		TNameSize	INT	3	0	
66 0		TaskName	Task_Name_eCLR	1028	0	
